apiVersion: apps/v1
kind: Deployment
metadata:
  name: sejutacita-db-deployment
  labels:
    app: sejutacita-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sejutacita-db
  template:
    metadata:
      labels:
        app: sejutacita-db
    spec:
      containers:
      - name: databaseserver
        image: sejutacita-db
        ports:
        - containerPort: 3306
        imagePullPolicy: Never