apiVersion: v1
kind: Service
metadata:
  name: sejutacita-db-service
spec:
  selector:
    app: sejutacita-db
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31111