apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 31115
  type: LoadBalancer
  selector:
    app: mongo